class connect:
    def __init__(self, **options):...
    def connect(self): ...
    def cursor(self): ...
    def executequery(self, query): ...
    def execute(self, fmt, data: tuple): ...
    def executemany(self, fmt, *data): ...
    def disconnect(self): ...
    def commit(self): ...